### ISSUE TITLE
"Run Accessibility Checks" is not executing

### ISSUE THREAD

**Issue by jasonday** [chromelens/chromelens#30]
No results on any site.

**Comment by ngzhian** [comment]
Thanks for letting us know, we will take a look over the weekend, and get back to you!
Meanwhile, aXe is a valuable tool for accessibility, it's recommended by Google's WebFundamental documentation now [0]. We are not actively maintaining this project right now, but do hop in to fix big issues like this. If you would like to help us out with this bug, it will be greatly appreciated!

[0] https://github.com/google/WebFundamentals/pull/4556

**Comment by ngzhian** [comment]
I've tried it on a couple of site and it works @jasonday , maybe it's because the extension didn't find any errors, and it also didn't give any output saying that it didn't find issues.
I've updated the new version to say "No errors" in the panel when there are no errors. You should get the update soon (v0.0.9)

**Comment by jin** [comment]
Closing this since 0.0.9 is release.
