### ISSUE TITLE
Improve the way we hide filter SVG to prevent white footer on pages

### ISSUE THREAD

**Issue by ngzhian** [chromelens/chromelens#9]
Based on work done in #4 , we fixed this problem 🎉 However as noted in a comment

>  Great catch! There is a concern about this, which is that we are adding a style tag to the current document, and that will affect the current document. Although it is unlikely that there will be an element on the page with id colorFilterSVG, we want to avoid that. I think using insertCSS will be a better solution.

Explore changing to using `insertCSS`.

@rongjiecomputer pinging in case you're interested :)

**Comment by rongjiecomputer** [comment]
After experimenting with a sample Chrome extension [stylizr](https://developer.chrome.com/extensions/samples#stylizr), I believe that even `insertCSS` is not the best solution: `insertCSS` inserts CSS rules in `injected stylesheet` instead of adding a style element into document, but the injected CSS rules will still merge/override the document's style.

Two possible solutions I have in mind:
- Use inline-style only: it avoids overriding completely, but painful to change the code.
- Wrap every CSS rules with a unique `id` like `#chrome-lens-base` and load it in a single style element when the panel is launched.

```css
#chrome-lens-base {}
#chrome-lens-base > #colorFilter {}
#chrome-lens-base > #colorFilter > #colorFilterSVG {}
#chrome-lens-base > .tooltip {}
...
````
I also noticed that in [run_axis.js](https://github.com/rongjiecomputer/chromelens/blob/master/run_axs.js), very general class names like `tooltip`, `tooltip-text` are used.

**Comment by ngzhian** [comment]
Thanks for looking into this, in that case I think solution 2 (wrap every CSS rule with a unique id) sounds better. It consolidates all our styles into a unique-enough namespace, and is also makes future changes way easier.
Yes I wrote that :ashamed: , we should probably use better names for that too! :)
